[package]
name = "mahjongkin"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
log = "0.4.22"
pretty_env_logger = "0.5.0"
teloxide = "0.12.2"
tokio = { version = "1", features = ["full"] }
